# Generated by Django 3.2.13 on 2022-05-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to='user/'),
        ),
    ]
