# Generated by Django 3.2.13 on 2022-07-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220701_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_billing_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_default_billing_address', to='main.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_shipping_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_default_shipping_address', to='main.address'),
        ),
    ]
